- hosts: all
  become: yes

  tasks:
  - name: Install OpenVPN
    apt:
      name: openvpn
      state: present

  - name: Generate server keys and certificates
    command: openvpn --genkey --secret /etc/openvpn/keys/ta.key
    args:
      creates: /etc/openvpn/keys/ta.key

  - name: Create server configuration file
    template:
      src: server.conf.j2
      dest: /etc/openvpn/server.conf

  - name: Create client configuration file
    template:
      src: client.ovpn.j2
      dest: /etc/openvpn/client.ovpn

  - name: Start OpenVPN service
    systemd:
      name: openvpn@server
      state: started
      enabled: yes
